name: RiasCore
version: '1.0'
main: de.satsuya.RiasCore
api-version: '1.20'
depend: [LuckPerms]
author: Satsuya

commands:
  freeze:
    description: Freeze or unfreeze a player
    usage: /freeze <player>
    permission: riascore.freeze
  assignworker:
    description: Add a player to a worker group
    usage: /assignworker <player>
    permission: riascore.assignworker
  removeworker:
    description: Add a player to a worker group
    usage: /removeworker <player>
    permission: riascore.removeworker
  serverstatus:
    description: Shows the Server status
    usage: /serverstatus <open|close|info>
    permission: riascore.setserverstatus
  resetdeaths:
    description: Shows the Server status
    usage: /resetdeaths <player>
    permission: riascore.resetdeaths
permissions:
  riascore.freeze:
    description: Allows the player to use the freeze command
    default: op
  riascore.assignworker:
    description: Allows leaders to assign a worker role to a player.
    default: op
  riascore.removeworker:
    description: Allows leaders to remove a worker role from a player.
    default: op
  riascore.allowlist:
    description: Allows a player to join the server while is closed.
    default: op
  riascore.setserverstatus:
    description: Allows a player to change the server status.
    default: op
  riascore.schmied:
    description: Allows crafting for armor and tools
    default: op
  riascore.fishing:
    description: Allows to fish
    default: op